# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/khangnghiem@gmail.com/deltabricks/resources/top_job_popularity")

# COMMAND ----------

display(spark.sql("SELECT * FROM dev.job_prospects.job_1900_silver"))

# COMMAND ----------


